### ISSUE TITLE
discretise_mutations() in msprime_extras no longer works

### ISSUE THREAD

**Issue by hyanwong** [mcveanlab/treeseq-inference#32]
Not sure if we want to keep this function anyway, since it buggers up ARGweaver inference (and I've flagged it up as such). So eventually it either needs correcting or deleting by @jeromekelleher (not urgently though) as at the moment it triggers the bug below:

```
Traceback (most recent call last):
  File "./src/plots.py", line 1682, in <module>
    main()
  File "./src/plots.py", line 1672, in main
    args.func(cls, args)
  File "./src/plots.py", line 1552, in run_setup
    f.setup(args)
  File "./src/plots.py", line 987, in setup
    super().setup(args)
  File "./src/plots.py", line 775, in setup
    self.data = self.run_simulations(args.replicates, args.seed)
  File "./src/plots.py", line 1026, in run_simulations
    replicate_seed, replicate_seed, discretise_mutations=self.JeromesDiscretise)
  File "./src/plots.py", line 876, in single_simulation
    ts = msprime_extras.discretise_mutations(ts)
  File "/Users/yan/Documents/Research/Wellcome/treeseq-inference/src/msprime_extras.py", line 93, in discretise_mutations
    msprime.Mutation(position=x, node=mut.node, index=mut.index))
AttributeError: 'Mutation' object has no attribute 'node'
```

**Comment by hyanwong** [comment]
We no longer discretise mutations in plots.py (we still do for ARGweaver, in ts_ARGweaver.py, but thats unavoidable)
